# a=input("enter the no:")
# b=input("enter the no:")
# len1=str(a)
# len2=str(b)
# if len2<len1:
#     print(len2+len1+len2)
# else:
#     print(len2+len1+len2)





    



# a=input("enter the number")
# m="0123456789"
# u="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# l="abcdefghijklmnopqrstuvwxyz"
# s="@#$%^&*!"
# i=0
# h=0
# c=0
# y=0
# z=0
# while i<len(a):
#     if a[i]in m:
#         h=h+1
#     if a[i]in u:
#         c=c+1
#     if a[i]in l:
#         y=y+1
#     if a[i]in s:
#         z=z+1
#     i=i+1
# print(h,c,y,z)


salary=int(input("enter the salary:"))
year=int(input("enter the year:"))
if year>5:
    a=year-5
    d=a*100
    print("bonus is",salary+d)
    
else:
    print("no bonus")





















    



    
    
    
    
    

    
    

    
    

    

